### ISSUE TITLE
Permission to upload images

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#10]
I can't upload an image files for a project's featured image.

**Comment by kimisgold** [comment]
I've gone and adjusted upload permissions. Try again and let me know if you're still having problems.

**Comment by sheilabrennan** [comment]
Yes, for a new page I created (A Liberian Journey). 
No, for pages I didn't (tried WebWise and Rebuilding the Portfolio)

This is the error message when uploading Featured Image: 
Unable to create directory wp-content/uploads/2013/12. Is its parent directory writable by the server?

**Comment by sheilabrennan** [comment]
Tried to upload a new profile photo, and file was not uploaded. No error message. 

I was able to successfully delete my current photo. Oops.

**Comment by kimisgold** [comment]
Okay, I apparently missed the directories for the plugin that manages profile pictures and 2013 uploads. They should be fixed now.
