### ISSUE TITLE
supporters page - skipped heading level

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#106]
WAVE is flagging the below as having a skipped heading level. It's currently an h4. Should this be an h2 instead? Currently, the only heading levels on this page are h1 and h4

https://rrchnm.org/our-story/supporters/
![Screen Shot 2020-10-12 at 4 56 12 PM](https://user-images.githubusercontent.com/618307/95789730-0acc4700-0cac-11eb-8c1f-8070a2e5d454.png)

**Comment by kimisgold** [comment]
Changed within the content.
