### ISSUE TITLE
annual reports individual pages - javascript jump menus

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#109]
similar to the News and News archive pages, the menu drop down needs an adjacent Go button as WAVE is alerting to javascript jump menus.

i.e: https://rrchnm.org/news/annual-report-2016-2017/attachment/rrchnm-annual-report_2016-17-2/

**Comment by kimisgold** [comment]
The annual reports should now directly link to the files, eliminating the attachment view.
