### ISSUE TITLE
'What We Do' should show featured projects and link to ongoing projects

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#11]
"Work In Progress": can we change this to "Our Work"?

All of the projects listed are finished projects. Perhaps there could be another category for works in progress (ie, Tropy)?

**Comment by kimisgold** [comment]
Ahh, so right under "Work In Progress" should be 3 currently active projects to highlight—I missed this when transferring content over from wireframes.

Do we still want to highlight these WIPs here? I think the initial reasoning was to show that the center is active and constantly working on new projects. If so, I'll figure out a way to flag projects for featuring here.

**Comment by sheilabrennan** [comment]
Ah. Yes. This would be where things like Tropy and the LC learning app would go.

**Comment by srob4757** [comment]
Yes, we definitely want to provide a pathway to information on WIP. The content on the google doc is "For upcoming projects, check out our Work in Progress." The idea was that would link to project announcement posts tagged WIP from the Center blog, for projects that did not have a site that could be included in the main collection of projects. Once a project had a site, it would be switched from WIP into the main collection.

**Comment by srob4757** [comment]
In the Google doc layout, the heading came after the text beginning 'In twenty-plus..' and was 'Explore Our Projects' (it could be Explore Our Work ), and intended as a heading for the filtered display of project information. Is there a reason not to layout the page like that?

**Comment by srob4757** [comment]
Its not clear in the notes on the Google doc, but default for the filtered view of the projects should be projects tagged 'Featured'. I thought we settled on which projects should be tagged Featured, but I can't find that list anywhere. They would be our best known, most highly trafficked projects - Zotero, Omeka, Teachinghistory.org, and some others. We decided to keep that group at about 6-8 projects, with some from each division

**Comment by srob4757** [comment]
There are a couple of projects in the list that shouldn't be there - DH Training & Professional Development and Contracts and Consulting. They are both superseded by the new page on Working with Us

**Comment by srob4757** [comment]
Kim, could you add the text "For upcoming projects, check out our Work in Progress" and the heading Explore Our Work (as in the Google Doc). We also need a Work in Progress tag in the blog to provide the content -- there are posts on Tropy, Eagle Eye Citizen, the Eisenhower e-memorial, and Omeka for Close and Distant Reading that can be tagged Work in Progress (and some other WIP that does not seem to have been announced on the center blog - Mapping Early American Elections? Through the Doors of Stratford? Omeka for Art Historians?)

**Comment by kimisgold** [comment]
I've incorporated the above comments, and they're ready for review on the "What We Do" page.
