### ISSUE TITLE
copyright - list

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#112]
https://rrchnm.org/copyright/

WAVE is alerting to the [list ](https://webaim.org/standards/wcag/checklist#sc1.3.1)on this page. Below is what it's saying to fix it. 
![Screen Shot 2020-10-13 at 12 53 39 PM](https://user-images.githubusercontent.com/618307/95891492-22123f80-0d53-11eb-9be1-6d9d2fcbddaa.png)

**Comment by kimisgold** [comment]
This has been fixed within the Wordpress admin.
