### ISSUE TITLE
author page - skipped heading level for project titles

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#113]
I think I may have missed this, but if not, please close ticket. Should the h4 be an h3 here?

where i found it: https://rrchnm.org/author/stephen-robertson/

![Screen Shot 2020-10-14 at 1 45 42 PM](https://user-images.githubusercontent.com/618307/96025833-b3e97d80-0e23-11eb-8ba8-9e4feff14841.png)

**Comment by kimisgold** [comment]
I've stopped using headings for the project titles, as the titles are more labels than section descriptions. They should now have the same presentation but use simple spans instead of heading elements.
