### ISSUE TITLE
search results - image title consistency

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#115]
When using the search feature, the images show "avatar for". In https://github.com/chnm/rrchnm-wordpress/issues/102, we established other images having "profile picture for..". I think the same should apply here

example:
![Screen Shot 2020-10-15 at 11 39 57 AM](https://user-images.githubusercontent.com/618307/96153006-2bc6af00-0edb-11eb-837d-4ba87c590708.png)

https://rrchnm.org/?s=news
https://rrchnm.org/?s=annual+report

**Comment by kimisgold** [comment]
This should now be in line with the other avatar markup.

**Comment by IdaAkiwumi** [comment]
This is looking good, however WAVE is saying 2 nearby images have the same alt text. 

![Screen Shot 2020-10-19 at 10 28 48 AM](https://user-images.githubusercontent.com/618307/96464527-ef09f900-11f5-11eb-9d9f-cef6700ac210.png)
"profile picture for" is repeated. 
![Screen Shot 2020-10-19 at 10 29 28 AM](https://user-images.githubusercontent.com/618307/96464568-fcbf7e80-11f5-11eb-8928-6dbc72464bbd.png)


Example below:

search page used: https://rrchnm.org/?s=annual+report

**Comment by kimisgold** [comment]
The use of the wrong display name variable meant that all the alt text had blank spaces for names. It should now be fixed in https://github.com/chnm/rrchnm-wordpress/commit/23bd3670bd681bfd836637aa3999c434e33ea92e.
