### ISSUE TITLE
project filter/category view - skipped heading level for image

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#118]
This image has a skipped level here: https://rrchnm.org/category/projects/content/community-participation/#projects

![Screen Shot 2020-10-19 at 5 17 28 PM](https://user-images.githubusercontent.com/618307/96512770-fbf70e80-122e-11eb-9df5-db677780bd14.png)

**Comment by kimisgold** [comment]
This should now be fixed in https://github.com/chnm/rrchnm-wordpress/commit/2a818b3692524225dc5a10b44212cb0c4269f9d6, using the standardized project partial view.
