### ISSUE TITLE
project filter/category view - redundant links

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#119]
WAVE is alerting to the images and their captions as having redundant links.

https://rrchnm.org/category/projects/content/community-participation/#projects

**Comment by kimisgold** [comment]
The `category.php` view that powers the filtered projects wasn't using the new partial view with the improved markup. I think it's been fixed in https://github.com/chnm/rrchnm-wordpress/commit/2a818b3692524225dc5a10b44212cb0c4269f9d6.
