### ISSUE TITLE
community participation - project filter/category view - empty links

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#120]
WAVE shows there are 9 empty links on this page and I think they pertain to the project images (based on me removing the page styling)

![Screen Shot 2020-10-19 at 5 30 55 PM](https://user-images.githubusercontent.com/618307/96514086-28138f00-1231-11eb-9f73-789b1d01dbb8.png)

**Comment by kimisgold** [comment]
Could you provide the page link?

**Comment by kimisgold** [comment]
Never mind, I see what you're talking about now.

**Comment by IdaAkiwumi** [comment]
https://rrchnm.org/category/projects/content/community-participation/#projects
