### ISSUE TITLE
collaberate - orphaned form label

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#121]
https://rrchnm.org/collaborate/

WAVE is alerting to all the fields on this page as having orphaned labels.
![Screen Shot 2020-10-19 at 5 56 55 PM](https://user-images.githubusercontent.com/618307/96516100-7f672e80-1234-11eb-96cf-5778df1121ac.png)

and this is what WAVE is saying about it:

![Screen Shot 2020-10-19 at 5 58 44 PM](https://user-images.githubusercontent.com/618307/96516253-c81ee780-1234-11eb-8489-8a2dbe7756b3.png)

**Comment by kimisgold** [comment]
This is part of #123, so I'm going to close this.
