### ISSUE TITLE
Create filter and separation for "affiliated" staff

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#13]
Can we separate the affiliated folks from the main staff grouping, like the alums?

**Comment by kimisgold** [comment]
Sure can. Quick question: do we want alums and affiliated members to appear in the user filters as well? If so, maybe we should create a reference for tagging those users.

**Comment by sheilabrennan** [comment]
Good question--probably for others to chime in as well.
A filter sounds like a good option.

**Comment by srob4757** [comment]
Yes, we definitely need to separate out the affiliated staff as the alumni are now - and if they appear, a filter sounds like a good idea
