### ISSUE TITLE
We Are Collaborative page content

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#16]
We have some drafted content that should replace much of what is on this page. I'm going to put it in below. Once its up, we can get some additional feedback on it.

Replace "Here are a few of our recent collaborations and partnerships." with "Since our founding in 1994, we’ve had the pleasure of collaborating with many individuals, organizations, and institutions on grant-funded projects as well as contract work."

Replace "Grant Supporters" with "Collaborating on Grant Applications"
Add this text: "Looking for collaborators for a grant proposal? We work with a range of partners to apply collaboratively for funding to create new digital projects, contributing history content creation, design and development of databases, websites, exhibits, and online courses, professional development workshops for teachers and faculty, and collaboration on existing tools or projects."
Keep list of projects

Add heading: "Recent Examples"
Keep the list of projects (although Bracero and Gulag are not recent)

Replace "Contract" with "Contract Work"
Add text: "Looking to develop digital tools, build or redesign a website, construct a digital collection or online exhibition, create teaching resources, provide training in the use of digital technologies, plan workshops or conferences, or develop a digital and social media strategy? We can help."

Add heading: "Recent Examples"
Keep the list of projects

**Comment by kimisgold** [comment]
Content has been updated.
