### ISSUE TITLE
Work With Us Button

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#18]
This needs to go to an as yet undefined contact page / form - which is where we could ask for what would we want someone seeking to collaborate with or contract us to have thought about, prepared before they contact us? EG, Need, Goals, scope of project, timeframe, funding (seeking or have in hand)

**Comment by kimisgold** [comment]
This issue is dependent on completing #24.

**Comment by srob4757** [comment]
The Work With Us page is a separate page from Contact Us - focused specifically on people seeking to work with us. I'm working with the directors on the content of this page. (The Contact Us page should have a Work With Us button to redirect anyone who ends up there)

**Comment by kimisgold** [comment]
The "Work With Us" form has been implemented here: http://dev.chnm.org/work-with-us/
