### ISSUE TITLE
Staff tags

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#20]
Given the wide audience for the site, could "Development" be "Software Development"?
And GRA be "Graduate Research Assistant"?

**Comment by kimisgold** [comment]
Fixed.

**Comment by sheilabrennan** [comment]
Discussing about the staff tags today at the table, there is overwhelming opposition to the staff roles.I agree, that it just doesn't seem necessary.

**Comment by sheilabrennan** [comment]
I'm going to ask for a conversation about the staff tags. These categories were never finalized, and most I do not find useful.

For example, why are we separating GRAs from DH Fellows, but not also listing Presidential Fellows or the Toynbee fellow? I'd really like there to be one category. What does "research" mean in this context? What does Staff mean in this context? And, why does it matter if we are also using the roles?

    Affiliate
    DH Fellow
    Director
    Faculty
    Graduate research assistant
    Research 
    Staff

**Comment by srob4757** [comment]
Yes, there should be a discussion of these tags. I assume that Chris came up with these as a working list. The separation of DH fellows is based on them not being GRAs - they are at the Center doing a practicum for credit, whereas the Toynbee and Presidential Fellows are GRAs. I'm also confused by Research
