### ISSUE TITLE
Additional content for Our Story

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#21]
We wanted to incorporate this material the Our Story page :

History [http://20.rrchnm.org/about] 

Thanks, Roy [http://thanksroy.org]

Digital History: A Guide to Gathering, Preserving, and Presenting the Past on the Web [ link to chnm.gmu.edu/digitalhistory/]

Essays in History and New Media [http://chnm.gmu.edu/essays-on-history-new-media/essays/]
Essays focusing on the theoretical and practical aspects of taking history into a digital format.

**Comment by srob4757** [comment]
And DH Fellows Program

**Comment by kimisgold** [comment]
The content has been included here: http://dev.chnm.org/about-us/. Further edits should be their own issues.
