### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#24]
Could this link to a page that provides our address and phone numbers, driving directions, and a number of different email addresses (Directors as well as the general address), with some explanation of when to use each?

**Comment by kimisgold** [comment]
That's fine. If someone can create that content, I'll post it and lay it out.

**Comment by srob4757** [comment]
I've added a page of google doc with content to the Basecamp project

**Comment by kimisgold** [comment]
The content has been formatted and posted here: http://dev.chnm.org/about-us/contact-us/

**Comment by srob4757** [comment]
Thanks - there's a missing colon in the url for the DH Fellowship

**Comment by kimisgold** [comment]
URL fixed.
