### ISSUE TITLE
Headings grammar

### ISSUE THREAD

**Issue by stakats** [chnm/rrchnm2016#35]
Current heading of "Who We Work With" is bound to rub a lot of people the wrong way, not just me. Making it "whom" would of course be even worse. Suggest new headings as follows:

Who We Are -> People
What We Do  -> Work [or Activities or Projects, etc.]
Who We Work With -> Partners [or Collaborators]

One bonus of this renaming is that "About Us" is no longer seemingly redundant (because right now it sounds exactly like "Who We Are").

**Comment by zerocrates** [comment]
"Those With Whom We Work"

**Comment by zerocrates** [comment]
Part of the gimmick with those headings is that they're "answered" by the titles or slogans or whatever they are on each page:

* Who We Are: We are Multifaceted
* What We Do: We are Innovative
* Who We Work With: We are Collaborative

Would you eliminate or alter those as well?

**Comment by stakats** [comment]
"Who We Work With" is currently answered with "Who We Work With". If they're meant to be questions, maybe we could make them questions, e.g. the truly existential Who Are We? 

Anyway, I understand that this potentially upsets the Q&A conceit, but is that rhetoric really necessary? I mean, there are probably a million organizational sites with exactly these heading titles; is there a significant upside in being clever here?

**Comment by srob4757** [comment]
I agree that the grammar is clumsy. So let's make them questions:  Who Are We - What Do We Do - Who Do We Work With

The Who Do We Work With page should be headed We Are Collaborative

**Comment by sheilabrennan** [comment]
We are starting to get into longer navigation headings, which is generally something we wouldn't recommend for another organization. For the purposes of easy to use and read navigation, I'd argue for shorter headings. Something like People | Projects | Collaborators

Then the heading for each landing page could be one of those statements, ie 
People / Who We Are 
Projects / What We Do
Collaborators / Work with Us

**Comment by kimisgold** [comment]
Headings have been updated according to the directors' content document.
