### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#37]
As per the Google Doc:

About Us should be Our Story - in the menus, and as the title of the page

Our Story in the left menu on the page should be History

The menu order should be: History - Our Founder - Digital History Fellowship - Essays - Digital History - Contact Us

**Comment by kimisgold** [comment]
These have been updated.

For future reference, all users with admin capabilities in the Wordpress can modify post content and menus. This menu can be accessed through Appearance > Menus > About Us Menu.
