### ISSUE TITLE
Alternatives to Multifaceted

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#4]
While the description is appropriate, I think the word itself is opaque and a little hard to decipher on the site itself. 

Could any of these be alternatives to consider: 

Talented
Versatile
Skilled
Resourceful

**Comment by sharonmleon** [comment]
One vote here for Versatile.

**Comment by srob4757** [comment]
OK, no one seems to have a problem with this change - so let's change multifaceted to versatile

**Comment by kimisgold** [comment]
Fixed in 8a33f74.
