### ISSUE TITLE
Who We Are - By Position

### ISSUE THREAD

**Issue by srob4757** [chnm/rrchnm2016#40]
We don't need "Research" in this list. (and at the moment when you filter By Division using Research, it adds a total to both Research in Role and Research in Position)

We do need "Alumni" to pick up the division (in addition to Affiliate)

Let's replace "DH Fellow" with the broader "Graduate Student"

**Comment by kimisgold** [comment]
The multiple active 'Research' filters should be fixed now. Also, now only populated filters will appear, so if there is anything missing, it's because no users have identified themselves using those filters.

Can you clarify what you mean by "Alumni" picking up the division?

**Comment by srob4757** [comment]
Sorry, that was completely opaque - I meant we need Alumni as a filter in addition to having the Alumni in a separate section on the default display. Does that make sense?

**Comment by kimisgold** [comment]
Yes. Alumni is now a 'Position' tag definable in user settings, so I went through and applied the tag to each of the old user accounts to populate the tag and have it appear in that left navigation. Because we have this, we no longer have to use the 'Active' checkbox that previously defined alumni.
