### ISSUE TITLE
Who we are

### ISSUE THREAD

**Issue by kschrum** [chnm/rrchnm2016#42]
Are these alphabetical by first name by design? 
Should we add GRAs to divisions for the year?

**Comment by kschrum** [comment]
I'm missing from administration; the other directors are listed there.

**Comment by kschrum** [comment]
I'm missing from most categories. Can you please let me know how to edit my categories?

**Comment by kschrum** [comment]
Graduate students are not tagged as such; most aren't showing up under "graduate student"

**Comment by kimisgold** [comment]
All users who aren't tagged haven't logged into Wordpress and tagged themselves. I could go through and tag users appropriately, but I'd need some kind of database of how all users should be tagged.

Alphabetical by first name is Wordpress's default sorting. Do we want to sort by last name?

**Comment by srob4757** [comment]
We've been waiting for folk to complete their own profiles - I'm happy to take care of the basic tagging, and yes, GRAs should be added to the division they are currently working in

**Comment by kschrum** [comment]
I'm not sure it was clear that folks should go in and look at their own profiles. I can talk with my team, but could you send a general message out to let people know? It would be great to get pictures for those missing individual headshots. 

I'd recommend giving some guidance as well. Pick the 1 or two tags that most represent the work you do. Most CHNMers do many things, so what is the one thing (or two things) that describe the majority of your work.

It would be helpful to send out the url and what to do if you don't have a login.

**Comment by kimisgold** [comment]
The <a href="https://chnm.basecamphq.com/projects/372328-website/posts/98636745/comments">basecamp message</a> was a follow up to the morning meeting where I requested everyone go into the staging site to update their tags. I mentioned that everyone that has an account on the currently active CHNM website had their accounts imported into the staging site, so the same username and password should work. I'll send out a reminder message on basecamp, along with <a href="https://github.com/chnm/rrchnm2016/wiki/User-Tagging">more explicit instructions</a> as to how everyone should update their tags.

**Comment by kimisgold** [comment]
Looking into it, apparently the message only went out to those who were part of the Website group on Basecamp. I'll post instructions in General.
