### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by kschrum** [chnm/rrchnm2016#43]
Footer is somewhat unwieldy. Is there a plan for streamlining/simplifying this?

![footer](https://cloud.githubusercontent.com/assets/8569125/16874665/91db7802-4a68-11e6-946b-a78d17cfdfd1.png)

**Comment by kimisgold** [comment]
There've been a few discussions regarding the footer in closed issues. I'll keep this one open until the content is finalized.

Tagging @srob4757 and @sheilabrennan, who'd been involved in previous discussions.

**Comment by kimisgold** [comment]
The footer content has been updated. If there are no further comments by 8/1, the issue will be closed.
