### ISSUE TITLE
Edit User

### ISSUE THREAD

**Issue by kschrum** [chnm/rrchnm2016#44]
Why are these fields required:

• Job Title
• Phone
• Level

Job title is addressed by position. Phone seems unnecessary. 

Level is problematic  - it defaults to director and there aren't enough options. Can we add a default "none"? Or not require it?

**Comment by kimisgold** [comment]
These are all older user fields that carried over from the current site. I agree Phone and Level shouldn't be required, and I've turned the requirement off for those fields.

'Job Title' allows for specificity beyond what the user taxonomies provide. For example, while I fall under 'Staff' for Position and 'Design' for Role, being able to specify my specific job as "Web Designer" is helpful. There are many different job titles amongst the center, beyond what I think would be helpful should they be included as filters.

**Comment by kschrum** [comment]
That makes sense. Can we make "job title" optional, though? Some people have a more specific title; some don't.

**Comment by kimisgold** [comment]
Yup, it's now optional.
