### ISSUE TITLE
Need ability to edit/delete picture on user profile

### ISSUE THREAD

**Issue by kschrum** [chnm/rrchnm2016#46]

**Comment by kimisgold** [comment]
Does this appear correctly on your user profile?

<img width="422" alt="screen shot 2016-07-25 at 1 06 34 pm" src="https://cloud.githubusercontent.com/assets/606764/17110022/b4325e0e-5268-11e6-9033-fb8b52695db3.png">

**Comment by kschrum** [comment]
Nope. Here is one from my user, connecting to Gravatar. And another from Sameera's where my image showed up.
![image](https://cloud.githubusercontent.com/assets/8569125/17110093/2c812516-5269-11e6-8945-422190bf1902.png)
![image 2](https://cloud.githubusercontent.com/assets/8569125/17110095/2e17b926-5269-11e6-8330-1309fe9e8c83.png)

**Comment by kimisgold** [comment]
That's the profile picture field that's built into Wordpress and relies on Gravatar. The custom picture field we use throughout the site is further down the form under "Extra Fields" after the "Podcast" field.

**Comment by kschrum** [comment]
What about deleting the first one if we're only pulling the 2nd one? The duplication will be confusing to new users.

**Comment by kschrum** [comment]
For Sameera, there is no image in the second one. It is automatically pulling my image from Gravatar and I can't delete it.

**Comment by kimisgold** [comment]
Even though that appears the case on the admin side, the public side doesn't ever use Gravatars, so Sameera's profile had a blank avatar. I've gone ahead and disabled use of Gravatars altogether.
