### ISSUE TITLE
Hub accounts

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#5]
Starting a list:

@ chnm
@ omeka 
@ wardeptpapers
@ mallhistories
@ zotero
@ teachinghistory

https://www.facebook.com/omekaRRCHNM

**Comment by kimisgold** [comment]
These seem to be twitter-only. Do we have accounts from other platforms we want to include?

**Comment by sheilabrennan** [comment]
Probably--I'll let others who know those contribute.

**Comment by srob4757** [comment]
https://www.facebook.com/mallhistories
http://mallhistories.tumblr.com
https://www.facebook.com/PopularRomanceProject 
@popularromance
https://www.pinterest.com/popularromance/
@pressfwd
https://www.facebook.com/Teachinghistory.org/?ref=ts
@tropychnm
@thatcamp

**Comment by kimisgold** [comment]
I've started entering social media accounts, and I'm noticing that Twitter is our most populated and frequently updated platform. That makes sense, but we also don't include many images in our tweets, resulting in a wall of text. Facebook accounts aren't in there yet, but the most recently updated account is the Popular Romance Project back in April. Here's the current page: http://dev.chnm.org/the-hub/. I'm a little concerned about how text-heavy this will be.

**Comment by sheilabrennan** [comment]
Yeah, it is text-heavy. There are dormant projects that had more social media content with images than what we have now. I wonder if the Hub is really necessary. 

Users can follow the Center, which is great.

**Comment by srob4757** [comment]
No doubt very text heavy at present. But our social media hasn't always been so text heavy, and won't necessarily be going forward, depending on our future projects. We can also ask folk to try to include more images in their tweets.
