### ISSUE TITLE
Works in Progress, Posts Tag or Category?

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#50]
@srob4757 @kimisgold Can you remind me how the Works in Progress stuff should work?

I've added a post in the new site for Mapping Early American Elections, which is a work in progress--there is no project site yet. 

There isn't currently a category or tag for this yet. 

Do I add project-related categories to it (funder, type), and add a new cat for Works in Progress? Or is it a tag for posts?

**Comment by srob4757** [comment]
There is a (slightly obscure) tag - '"wip"
