### ISSUE TITLE
Null user in staff page?

### ISSUE THREAD

**Issue by mebrett** [chnm/rrchnm2016#6]
There's a blank user logo on the staff categories pages, even when there's an actual user assigned to them - see http://dev.chnm.org/tag/role/development/.

Also, if there's only one user in a category, the actual person and the place holder user are spread out rather than side by side (I'm not sure if the weird spacing is due to the placeholder image or if it would look the same with two actual users). See http://dev.chnm.org/tag/role/outreach/

**Comment by zerocrates** [comment]
`justify-content: flex-start` will pack short lines of users to the left, if that's what's desired.

**Comment by kimisgold** [comment]
Mystery user should also be gone.
