### ISSUE TITLE
Update "Upcoming Events"

### ISSUE THREAD

**Issue by dhowlett1692** [chnm/rrchnm2016#63]
The upcoming event on the home page is for July 2019

**Comment by kimisgold** [comment]
* We need to update the website with more events.
* The header should nix "Upcoming" to avoid this scenario.

**Comment by kimisgold** [comment]
Documentation: https://github.com/chnm/rrchnm2016/wiki/Creating-Events

**Comment by kimisgold** [comment]
@dhowlett1692 
For this issue, please complete the following tasks:

* Talk to the directors about possible upcoming events to feature on the website.
* Create the event posts in Wordpress. I'd say if you accumulate more than 4 events, ask one of the RAs for help. Even if it's easy, it's good to have more people understanding this process.
