### ISSUE TITLE
Not all staff listed on who-we-are are in the author list

### ISSUE THREAD

**Issue by mebrett** [chnm/rrchnm2016#8]
They may be listed as users but they don't show up in the auto-populated list when I go to add an author to a project.

**Comment by mebrett** [comment]
Specific instances (that I can find):
- Lindsey B. 
- Andrea Ordine
- Jenny Reeder

**Comment by sheilabrennan** [comment]
Yes, this is a challenge, because it would be nice to associate alums with their work at the Center--especially for some of the legacy projects

**Comment by kimisgold** [comment]
Ah, for whatever reason these users weren't assigned a role. They now have Editor status like everyone else, and should be addable as authors.
