### ISSUE TITLE
Text size in NAH logo in footer

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#81]
Size is small and may require the user to zoom in on page to read. Make sure any text in images of text is at least 14 points and has good contrast.

**Comment by kimisgold** [comment]
Due to its nature as a logo file, I think it may be exempt. I'm looking at the [W3's guidance on this](https://www.w3.org/WAI/tutorials/images/functional/#image-used-alone-as-a-linked-logo), specifically in the second note.

**Comment by IdaAkiwumi** [comment]
It may be exempt, but we should probably consider "Logotypes (text that is part of a logo or brand name) are considered essential." as referenced on [W3 Images of Text Success Criterion](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html). So from their note on Functional Images, it doesn't necessarily need to be 14 point (size requirement), but being that it's essential, having the text (National Endowment For The) in it be a bit more clear would aid in accessibility for those with low vision.

**Comment by kimisgold** [comment]
I checked and thankfully NEH updated its branding to use more legible text. I've updated the footer with the new seal.
