### ISSUE TITLE
CSS Content Alert

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#83]
I decided to triple check the first page, and I just noticed the below alert on ANDI and here's the [page ](https://www.ssa.gov/accessibility/andi/help/alerts.html#pseudo_before_after)it links to for further information about the alert.

I'm not sure if this is a real issue, but wanted to give a head's up.

![Screen Shot 2020-09-29 at 3 32 03 PM](https://user-images.githubusercontent.com/618307/94607440-ea42cc80-0269-11eb-8e85-c7f79e5b0157.png)

**Comment by kimisgold** [comment]
Could you link to the page on which this alert appears?

**Comment by IdaAkiwumi** [comment]
Oh sorry about that. It's the main page: https://rrchnm.org/. I also took a quick glance at a couple other menu items and the alert shows up on them too, so it's safe to assume it's on the entire site.

**Comment by kimisgold** [comment]
I noticed that ANDI flags all pseudo-selector content, regardless of usage; the way it's used on the site is purely decorative, so I think we're in the clear as the alert is worried about content missable by screen readers.
