### ISSUE TITLE
RRCHNM logo naming - footer

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#85]
The NEH logo made me think a bit more about the RRCHNM logo. I realize the logo at the top of the page has the full name of the department in the code, but the one at the bottom is abbreviated as "RRCHNM logo". I'm more inclined to say that name should also be fully spelled out based on what I read here: https://www.w3.org/WAI/WCAG21/Techniques/general/G102.html. What are your thoughts?

**Comment by kimisgold** [comment]
This makes sense and is an easy change.
