### ISSUE TITLE
 homepage- 2019 CHSS Celebration of Achievement section

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#86]
The post itself was made back in 2019, however the link to RSVP and the text surrounding that link make it seem like it's still possible to RSVP. Is it possible to either remove/hide the RSVP section or maybe say "Interested guests were asked to RSVP here by October 3rd, 2019."?

**Comment by kimisgold** [comment]
Changed the copy to "were asked".
