### ISSUE TITLE
homepage - possible empty link on page

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#88]
While using the [WAVE](http://wave.webaim.org/) tool, I was alerted to there being an empty link on the page.
![Screen Shot 2020-09-30 at 3 34 21 PM](https://user-images.githubusercontent.com/618307/94731233-73253b00-0332-11eb-8250-16f0c2c8eb17.png)

This is the link that seems to be empty, but I'm not sure if there's another way to present this link `<a href="#" class="mobile-toggle"></a>` 

I read this [article](http://paintincode.blogspot.com/2012/03/dont-use-to-create-empty-links.html), that says to code empty links like this: `<a href=”javascript:void(0);”>link</a>` so does it make sense to code the above like this: `<a href="javascript:void(0);" class="mobile-toggle"></a>`  ?

**Comment by kimisgold** [comment]
This was the mobile toggle button. I added a span with `aria-hidden="true"` for the icon as well as a screen reader only span for the label itself, following the [recommended markup pattern for accessible icon fonts found here](https://css-tricks.com/can-make-icon-system-accessible/).
