### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by sheilabrennan** [chnm/rrchnm2016#9]
Jobs: Do we want to keep this in the footer permanently? We don't often have any available. We could keep a page and link to it from both About and Who We Are.

Creative Commons License: This is missing from the current footer.

**Comment by kimisgold** [comment]
Would the Creative Commons License be separate from the Terms of Use, or are they the same?

**Comment by sheilabrennan** [comment]
It would be different. I'm not quite sure what the Terms of Use would be. 
The more I look at what is in the existing footer, the more I see this is a question to ask of a bigger group. 

The question is do we need to replicate what exists on the current RRCHNM footer site. Or can we do include copyright notice for site and then have one link to all of policies. 

Copyright notice for site content (CC-BY-SA)
User-generated content policy, http://chnm.gmu.edu/about/rr-chnm-user-generated-content-policy/, Request form to use of project content, http://chnm.gmu.edu/requests/
Copyright policy as related to Center projects, http://chnm.gmu.edu/copyright/.

**Comment by srob4757** [comment]
Jobs shouldn't be there.

Not sure where Terms of Use came from - I think the footer should replicate what is on the existing site

**Comment by srob4757** [comment]
Can we add the NEH logo here? The accompanying text should be "RRCHNM is supported in part by an endowment made possible by National Endowment for the Humanities Challenge Grants" (NEH asked for this)

**Comment by srob4757** [comment]
Kim, can we go ahead and put in the information from the current footer - the CC-BY-SA license and links to the policies, with the NEH logo as well as acknowledgement. And then we can see if we need to follow Sheila's suggestion and consolidate the policies in a single link
