### ISSUE TITLE
who we are page - all staff images and names - adjacent links

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#90]
According to the WAVE tool, there are numerous adjacent links pertaining to the staff images links and the links on the names.  A screenreader would read both links twice and as they are the same link, it slows down navigation. More info can be found here: https://www.w3.org/WAI/WCAG21/Techniques/html/H2

This is happening with all the staff image and text name links. 
![Screen Shot 2020-10-05 at 4 12 38 PM](https://user-images.githubusercontent.com/618307/95127215-a64a3e80-0725-11eb-887d-1395231c499b.png)

More info from WAVE tool:
![Screen Shot 2020-10-05 at 4 15 05 PM](https://user-images.githubusercontent.com/618307/95127420-f6290580-0725-11eb-8d3b-df0195812130.png)

**Comment by kimisgold** [comment]
This is ready for testing.
