### ISSUE TITLE
mobile view - navigation - hamburger icon & menu view

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#92]
Writing this now before I forget. 

Right now, I think the hamburger menu could use updating. From our conversation, we were thinking ensuring the header is always in view when the menu is active (showing logo, magnifying glass, hamburger menu close icon) and having the hamburger icon change when it has been selected. The icon could be X which visually tells the user that tapping X will close the menu. We can also explore other options.

**Comment by kimisgold** [comment]
These changes have been applied: 

* Header always present.
* Mobile menu takes up the full width of the page.
* Menu toggle button changes to "X" to indicate close action when menu is open.

**Comment by IdaAkiwumi** [comment]
This is looking great! Only issue here is with the header being present always, when menu is open and the search icon is tapped, the search box pops up behind the menu. The user is still able to type and press enter on their keyboard, but the text field and button aren't seen.

**Comment by kimisgold** [comment]
The mobile menu adjustments for toggling search should be live now.
