### ISSUE TITLE
supporters page - table needs <th> cells

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#93]
https://rrchnm.org/our-story/supporters/ 

ANDI shows a table alert saying it has no <th> cells. Further info here: https://www.ssa.gov/accessibility/andi/help/alerts.html#table_has_no_th

![Screen Shot 2020-10-06 at 12 11 25 PM](https://user-images.githubusercontent.com/618307/95228328-30011700-07cd-11eb-8661-b28fba51b1d0.png)
![Screen Shot 2020-10-06 at 12 15 57 PM](https://user-images.githubusercontent.com/618307/95228910-e95fec80-07cd-11eb-815a-6434b5a44dec.png)

**Comment by kimisgold** [comment]
This shouldn't really be a table. I've styled it to have the 3 column layout using regular text content markup.
