### ISSUE TITLE
the hub - empty links?

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#96]
WAVE is alerting to the page having 15 empty links. I think it's referring to the icons below each post? 
![Screen Shot 2020-10-06 at 1 01 03 PM](https://user-images.githubusercontent.com/618307/95235890-29c26900-07d4-11eb-9389-346fd6d50174.png)

**Comment by kimisgold** [comment]
I'm going to let this one go because the markup is generated by Flow Flow, a third-party plugin. I've at least started [a topic for it at their support forums](https://wordpress.org/support/topic/provide-accessible-text-on-twitter-action-links/#new-topic-0).
