### ISSUE TITLE
the hub - color contrast on Twitter button and text links

### ISSUE THREAD

**Issue by IdaAkiwumi** [chnm/rrchnm2016#97]
ANDI is alerting to color contrast issues with the Twitter buttons and the blue links within the tweets. I recommend using Twitter's color: #1da1f3 from their guidelines: https://about.twitter.com/en_us/company/brand-resources.html and also bolding or thickening the button text.

**Comment by kimisgold** [comment]
I've configured the plugin to use the recommended color.
